### PR TITLE
Fix 64m dts to include spi clocks

### PR DESCRIPTION
**Pull request by dpavlin**
This makes build fully working on blue boards

### CODE REVIEW

**Comment by Dolu1990** [comment]
Cool thanks :D

**Comment by dpavlin** [comment]
I don't like two copies of dts file, and we can specify 64M memory using u-boot:
```
fdt add 0x81EF0000
fdt memory 0x80000000 0x04000000
saveenv
```
@lawrie would this be simpler solution?

**Comment by lawrie** [comment]
Yes, I agree that is a better way to tell Linux about the 64MB of memory. I will add it to the README.

**Comment by Dolu1990** [comment]
So, if i understand well => default set to 32 MB, and if you want 64 M you extend it  via uboot command line ?

**Comment by dpavlin** [comment]
> So, if i understand well default set to 32 MB, and if you want 64 M you extend it via uboot command line ?

Yap, it just modifies device tree loaded in memory before bootm using u-boot device tree support.

I would love if we could ask bootloader code (which knows how much memory there is) from u-boot, but looking at it my idea doesn't seem to fit in there :-)

**Comment by Dolu1990** [comment]
Sound good for me to ^^

**Pull request merged**
